### ISSUE TITLE
Unicode path encoding error in open_file_dialog

### ISSUE THREAD

**Issue by fschutt** [jdm/tinyfiledialogs-rs#17]
If I select a file in the file dialog and the file contains unicode characters, these character get replaces by `U+FFFD`, meaning that the resulting file path is useless:

```rust
let dialog_result = open_file_dialog("Open file", 
println!("{:?}", dialog_result);
```
prints:

```
Some("C:\\Users\\Felix Sch�tt\\Development\\azul\\assets\\svg\\test.svg")
```

Because of the `ü`, the file path returned from `open_file_dialog` is useless - I simply can't open any file. However, this might have to be reported to the original `tinyfiledialogs` developers OR it is the fault of this library using `to_string_lossy` - it would be better to escape the unicode characters.

So if I try to open a file using `fs::read_to_string()`, of course it can't find the file because of the � character.

**Comment by jdm** [comment]
Mmm, the API for tinyfd_openFileDialog returns a char*, but it's using an API internally that deals in LPTSTR, which can be either short or wide character strings depending on options at compile time. This could either be fixed at the tinyfiledialogs library level by ensuring that all outputs are UTF-8 compatible (or at least making a guarantee about a single encoding for all return values), or at the tinyfiledialogs-rs level by adding per-platform re-encodings.

**Comment by fschutt** [comment]
Well this issue only appears on Windows, so I've "fixed" it by switching to the nfd library on Windows and use tinyfiledialogs on Linux / macOS.

**Comment by Freaky** [comment]
This will be a problem on Linux as well if you have a path that isn't valid UTF-8.  Paths are not Strings.
