### ISSUE TITLE
Text in message boxes is passed to a shell without proper escaping

### ISSUE THREAD

**Issue by YtvwlD** [jdm/tinyfiledialogs-rs#19]
I wanted to display a message box with text that contained something like "invalid value \`foo\`".
But the resulting message box just said "invalid value".
And in my terminal I got the message `sh: 1: foo: not found`.

(This is on Ubuntu 18.04.)

**Comment by jdm** [comment]
I'm pretty sure this is a problem in the underlying C library, so I recommend reporting this upstream at https://sourceforge.net/projects/tinyfiledialogs/.

**Comment by wez** [comment]
This is a super scary issue; please consider adding escaping in this wrapper, and at the least adding a visible warning about it to your docs!

**Comment by YtvwlD** [comment]
Oh, I totally forgot to report this upstream.

**Comment by YtvwlD** [comment]
I did this and got a reminder to look at the documentation. It says:
> - Avoid using " and ' in titles and messages.

So, this is known upstream with no intent to fix.

**Comment by jdm** [comment]
I don't have a linux build environment handy, but I would accept a pull request to unsafe escape characters on linux.

**Comment by vareille** [comment]
Hi, I am the author of tinyfiledialogs. I've just corrected this security issue in version 3.8.0.
tinyfiledialogs now detects the single and double quotes in titles, messages and various parameters.
The dialogs are still displayed but the faulty parameters are replaced with a warning.
Let me now if I can help. thanks.

**Comment by SamMorrowDrums** [comment]
@vareille I've submitted a PR with version bump and it's working well for me.

**Comment by SamMorrowDrums** [comment]
@jdm sorry for the false "I've submitted" - finally clicked submit on PR :trollface:
