### ISSUE TITLE
Cannot save file within russian name folder

### ISSUE THREAD

**Issue by SargisParunakyan1** [jdm/tinyfiledialogs-rs#22]
` IntPtr pointer = tinyfd_saveFileDialog(sDialogTitle, sInitialPathAndFile, 
                filterPatterns.Length, filterPatterns, sPatternDesc);`

The pointer is always null when i am trying to save correpsonded file in folder which name is in russian or in any language which is not english. I was able to save file only in english named folder.

I am .Net developer and i was able to call this method through DllImport attribute 

` [DllImport("tinyfiledialogs", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr tinyfd_saveFileDialog(string aTitle, string aDefaultPathAndFile, int aNumOfFilterPatterns, string[] aFilterPatterns, string aSingleFilterDescription);`

**Comment by jdm** [comment]
This repository is only the Rust bindings to the tinyfiledialogs library. You should file this upstream at https://sourceforge.net/projects/tinyfiledialogs/.
