### ISSUE TITLE
Link failure on windows-gnu toolchain

### ISSUE THREAD

**Issue by Herschel** [jdm/tinyfiledialogs-rs#28]
Linking to shcore fails when using the windows-gnu toolchain:

`cargo run --example main`
`  = note: c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lshcore`

Commenting out the shcore line in build.rs allow the example to compile and run.
stable-x86_64-pc-windows-gnu 
rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by gyorokpeter** [comment]
Thanks. I checked out the project and made the similar change, now the build goes through fine. However every time I do cargo build or cargo run a screenful of warnings is printed out for that project. Is there a way to suppress this?
