### ISSUE TITLE
Request to publish version on crates.io with shell escape fix.

### ISSUE THREAD

**Issue by EkardNT** [jdm/tinyfiledialogs-rs#30]
#19 was closed by https://github.com/jdm/tinyfiledialogs-rs/commit/1a235d1b14f05354af23ecd0781dba2fe72fdd83 but an updated version has not been published to crates.io. Downloading the latest available version (3.3.10) of this crate reveals that it includes the broken 3.3.9 version of the C library. Therefore, this crate still breaks when passed a message that contains `'` or `"`.

Please publish a new version to crates.io (presumably 3.8.3 to match the C version) with the shell escape fix.

**Comment by jdm** [comment]
Published.
